topic_base_electromer: "keithley6517b"
device_name_electromer: "Keithley6517B"

topic_base_mass_filter: "qsource3"
device_name_mass_filter: "QSource3"

mqtt_broker: "rpi-quad"
mqtt_port: 1883
mqtt_connection_timeout: 60
